# Generated by Django 3.0.7 on 2020-07-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagramlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramlogin',
            options={'verbose_name_plural': 'Instagram Login'},
        ),
    ]
