# Generated by Django 3.0.7 on 2020-07-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagramlogin', '0002_auto_20200707_1245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstagramLogin',
            new_name='Instagram_Login',
        ),
    ]
